install.packages("quantmod")
#install.packages("quantmod_0.4-14.tar.gz", repos = NULL, type = "source")
install.packages("dplyr")
install.packages("plotly")
install.packages("lubridate")
install.packages("PerformanceAnalytics")
install.packages("highr")
install.packages("markdown")
install.packages("stringr")
install.packages("yaml")
install.packages("knitr")
install.packages("rmarkdown")
tinytex::install_tinytex()
